### ISSUE TITLE
In-between levels needed

### ISSUE THREAD

**Issue by shoc71** [shoc71/Keep-On-Going#270]
Mentioned from #217 opened my eyes to the possibilities of new levels that need to focus more on aesthetics and less on game-play (emphasis on the focus since this is more about the main branch than anything else)

**Comment by shoc71** [comment]
- [ ] more easy inbewteen levels needed towards the beginning (roughly 10) to get the players use the buttons and workings of the game like they are supposed to
- [ ] more levels to slowly eslcate the difficulty of the game making it doesn't get too diificult and the skill gap is too big from each level

**Comment by slysnivy** [comment]
@shoc71 This issue should be done as well.

**Comment by shoc71** [comment]
will be re-opened when this becomes an issue again
