### ISSUE TITLE
Adding #PR-numbers to the code/link being updated

### ISSUE THREAD

**Issue by shoc71** [shoc71/Keep-On-Going#302]
I think the "incorrectly labelled as" is unnecessary and confusing. If it's the PR title then we can change it. 
Furthermore, I was looking through the order and I don't understand to why some of them are incorrectly labelled. For example, dsn_class v.0.2.7 was in August 7-13 while dsn_class v.0.2.8 was in August 14-20, but was said to be incorrectly labelled as v.0.2.8 (it should be correct, unless I'm missing something)?

Another inconsistency is sometimes the files are named dsn_levels.txt and dsn_class.txt, when they're .py files.

I also think that it would be better to include the PR number (#nn) to better see which reference we're talking about (since the changes were done in date ranges)

_Originally posted by @slysnivy in https://github.com/shoc71/dont-stop-now/pull/301#pullrequestreview-1608539103_

**Comment by shoc71** [comment]
It's worth noting that two levels.txt were merged before this issue opened up and after patch notes were updated. 

- [ ] Add #297 and #300 to patch notes

**Comment by slysnivy** [comment]
@shoc71 We can close this since I don't think the log is that important currently

**Comment by shoc71** [comment]
we tried... we'll try and do better after the initial release and after the beta testing
