### ISSUE TITLE
Add tutorial letters and animation 

### ISSUE THREAD

**Issue by shoc71** [shoc71/Keep-On-Going#310]
Question?

do we want to make it animate idly in a loop? OR do we want to have it respond to the player's movement and tapping to incentive their activity?

- my answer is both; we have in the beginning play idly in a loop and then when the player begins, it responds to their movements and then after some time switch back to the idly loop function, if they are not able to solve it again.

> you have two images/frames showing pressed/unpressed.

First design and recommended

**Comment by slysnivy** [comment]
What is this for btw?

**Comment by shoc71** [comment]
we wanted pictures in the background for the tutorial, no?

**Comment by slysnivy** [comment]
Oh I see, then we can have it animate idly in a loop

**Comment by slysnivy** [comment]
@shoc71 I'm letting you know that we have an animation class. We just need the actual tutorial set up and what images to include like pressed and unpressed keys. I'll try to add rough sketches of what I mean soon.

**Comment by slysnivy** [comment]
Going to close this to open a more specific issue
