### ISSUE TITLE
Name change for the game

### ISSUE THREAD

**Issue by slysnivy** [shoc71/Keep-On-Going#313]
We'll need to change the repository name along with everything else to be "Keep On Going", or "KOG" (in short)

**Comment by shoc71** [comment]
there will be a new patch that will replace everything in order to rename all the other files. There is no other solution (rn) that i can think of. Will that be fine?

**Comment by slysnivy** [comment]
@shoc71 I will release a patch tomorrow with the name changes for everything _except for the image files_ under "kog_patch_18" (to continue our numbering, but under another name)
