### ISSUE TITLE
Add class for collectables

### ISSUE THREAD

**Issue by slysnivy** [shoc71/Keep-On-Going#316]
[Updated October 30th 2023]
This class will need to support:
1. In game:
- [x] Movement in the game (run away from the player/move on their own)
- [x] Animations of some sort
- [x] Collision detection with the player (interacting)
- [x] making them visible in the levels
- [x] a visible counter for the number of friends you have

2. In the code:
- [x] An optional "None" statement at the end for the parameters which could be used to add new features (like the none in Text)
- [x] pygame rect (maybe polygons) and imported images
- [x] Having connections with Memory (load_levels, all the level.txt's, and statistics as a count)

**Comment by shoc71** [comment]
wait why this is important?

**Comment by slysnivy** [comment]
I thought we needed some form of collectable right? Whether it be "friends", fuel packs, or any item we want the player to get throughout the levels. This class would allow the player to "collect" it, but be robust to include any specific things the collectable should be. I hope this clears things up.

**Comment by slysnivy** [comment]
This is how it looks so far. To me, it looks too small right? 😆 
![image](https://github.com/shoc71/Keep-On-Going/assets/47337807/0f3bc057-db32-4011-8d44-5c2de02a43a3)

**Comment by shoc71** [comment]
> This is how it looks so far. To me, it looks too small right? 😆. Right now it's size is 10 by 10, the same as the player

LMFAO. I think we should make the size of the stars at least 25x25 and see what happens. I will also re-edit the image pictures of the stars so that they look better.

**Comment by slysnivy** [comment]
> > This is how it looks so far. To me, it looks too small right? 😆. Right now it's size is 10 by 10, the same as the player
> 
> LMFAO. I think we should make the size of the stars at least 25x25 and see what happens. I will also re-edit the image pictures of the stars so that they look better.

![image](https://github.com/shoc71/Keep-On-Going/assets/47337807/a9e8047d-f20b-4de0-8e51-0e7a6dfdc5a9)

This is the size of the star at 25 by 25, any larger would make the star look significantly larger than the player. You can see that a lot of detail is lost, especially the black outline. My suggestion is to scale down the actual pixel art to a smaller size.

**Comment by shoc71** [comment]
Interesting, I'll take care of the actual size of the images themselves then. I will submit a bunch of pictures for testing and see which one works best for the program.
