### ISSUE TITLE
Pause Screen formatting and a way to access the options

### ISSUE THREAD

**Issue by slysnivy** [shoc71/Keep-On-Going#326]
When the player pauses in a level, they should be able change these settings on the go

**Comment by shoc71** [comment]
also need to make it look more clean.

**Comment by slysnivy** [comment]
@shoc71 I have an idea on how we could incorporate the pause screen dynamically in levels. It's not the most efficient method, but we can just render and blit the screen and associated options directly on top of the level while the game is paused. 

It's similar to the editor where adding text or selecting levels **doesn't change scene** but puts the game loop in an alternative state (text mode or select levels mode). 

Anyways, the general gist is to just overlay options on top of the level. Additionally since we have pause checks for the controls, the player can't control the square with A/D/SPACE, so it's ok to use those keys again for the settings (no conflict).
