### ISSUE TITLE
Check level_zero if it's correct

### ISSUE THREAD

**Issue by slysnivy** [shoc71/Keep-On-Going#343]
I looked over level_zero and I think there might be some stuff missing in the recent version. Please check it over just to be sure 👍

**Comment by shoc71** [comment]
Yeah, I agree with you. For some reason, it keeps crashing with or without content inside of the list. Gimme some time, I should have this working soon.

**Comment by shoc71** [comment]
think this issue is good to close as there is nothing else that should be a concern now
