### ISSUE TITLE
LevelZero text issue in self.display_clear_text

### ISSUE THREAD

**Issue by slysnivy** [shoc71/Keep-On-Going#351]
self.clear_text isn't defined anywhere in the init. Is it's init missing in LevelZero or is the method not being used?

**Comment by shoc71** [comment]
this was an attempt to use the display_clear_text function to work, which was originally the "victory_text" from the levelscene class but I made different functions to solve this problem, so this will be pruned out eventually when revisiting the code for optimization .

**Comment by slysnivy** [comment]
Ok, I'll remove the method in the next update and will close this issue now.
