### ISSUE TITLE
Add Placeholder Pictures (Or Multiple Pictures) for Animations

### ISSUE THREAD

**Issue by slysnivy** [shoc71/Keep-On-Going#395]
Keep in mind these placeholders can be like 2 images (2 frames) for a certain animation
These following steps are crucial for implementing the animations we want:
- [x] Plan out what animations we want to have (Right now we have tutorial instructions and NPC's)
- [x] Make an individual class for each type of animation we want (NPCAnimations/TutAnimations) that would use the Animate class, similar to how I did it with the Stars/Collectable class
- [x] Add the necessary methods/functions in the Animate class 
- [x] Implement it in their respective areas (Add NPCAnimations/TutAnimations to Hubzones and PlayLevels respectively in their init, render, and update), similar to how I did it with the Stars/Collectable class

**Comment by shoc71** [comment]
giving till end of 28th/nov/2023 to add all relevant images for this

**Comment by shoc71** [comment]
this issue can be resolved by adding a white backgrounds

**Comment by slysnivy** [comment]
Plan:
1. Have 2 frames representing each arrow keys for general MenuScene, LevelSelect/HubSelect, Hubzones, and OptionsPage use along with the tutorial levels. NPC's will use a default white square for now as filler for their other frames since their design is still a W.I.P.
2. NPCAnimate/AnimateNPC and ArtAnimate/AnimateArt should be good. 
3. The only main difference might be how their imported.

**Comment by slysnivy** [comment]
Changing the plan to have arrows and arrow keys to represent pressing the desired key instead of trying to make it pressed (for now)

**Comment by shoc71** [comment]
> Changing the plan to have arrows and arrow keys to represent pressing the desired key instead of trying to make it pressed (for now)

Agreed! Getting the images to merge together with the hands for now is going to take some time

**Comment by slysnivy** [comment]
Changed the plans to not have specialized classes for now since it they don't do anything special at the moment. That would be an issue separate from just adding images and making the animations work. Rather, we would just need a way to load the animations in for certain levels.
