### ISSUE TITLE
Scale down pictures of hands in the key_img folder

### ISSUE THREAD

**Issue by slysnivy** [shoc71/Keep-On-Going#433]
They are way too big to be reasonable scaled down to fit with the key_img's (it's better to scale up more, as you don't lose detail up to a certain point). You can see in the first level that it looks like this:
![image](https://github.com/shoc71/Keep-On-Going/assets/47337807/39e95966-1821-44b1-9404-4e3298b9df16)

**Comment by shoc71** [comment]
I am going to merge the two images together so they fit in that 64x64 ish pixel range

**Comment by slysnivy** [comment]
@shoc71 Do not merge the two images together. We want to add motion for each image independently. In this case, the finger would be bobbing up and down while the key is stationary

**Comment by shoc71** [comment]
> @shoc71 Do not merge the two images together. We want to add motion for each image independently. In this case, the finger would be bobbing up and down while the key is stationary

That's fair but it's super easy to do on my end or your end (depending on how you see it) so I thought it would be easier to call and refer, reducing the number of lines and code needed.

**Comment by shoc71** [comment]
On a related note, if 64x64 is not the ideal pixel size that you're looking for, please let me know. I tried re-scaling the images on Paint to check for quality and it seems to be perfect for 64x64 only.

**Comment by slysnivy** [comment]
> That's fair but it's super easy to do on my end or your end (depending on how you see it) so I thought it would be easier to call and refer, reducing the number of lines and code needed.

You missed my point where we need two separate images to have animations where one, the hand, moves to make it look like it's gesturing towards the other image, a stationary button that doesn't move. Unless you wanted me to write code to first split the image before adding the individual animations.
