### ISSUE TITLE
Rework KOG levels

### ISSUE THREAD

**Issue by slysnivy** [shoc71/Keep-On-Going#436]
- Level difficulty being either too easy or too hard, no in the between. There’s no sense of progression, even if they’re ordered. More specifically, no sense of progression in gameplay (difficulty and certain level elements, like new concepts are thrown in suddenly), setting (thrown in different types of themes, no story from worldbuilding being told), and progression (too easy or too difficult)
- A better way to go vertical using portals. I noticed that we have a lot of steps or bouncing ladder segments that take up a lot of space and rely on pure luck (correct position at the right time) to go up. These portals would just relocate the player to its corresponding side and keep the momentum of where they were going. This would both create more space for more level and art as well as remove the annoying segment of trying to scale up based on luck.
- Get a solid story down, if we don’t want one in our game, then ignore this point. If you already have one, then it’s needed for the more important part of basing your future levels off of these story elements. My biggest complaint is that all of these levels look like they’re just thrown together, no sense of where I came from and where I’m going and makes it so I’m less attached to the game as a whole. 
- Additionally, most of these levels feel disconnected, where the bare minimum of story I felt was in the lava hubzone with only the first few lava levels. Remember that these experiences should be memorable after playing the game (and I remember those lava zone levels the most). We can remedy this by including some important parts of previous levels in the next levels after them to show that you ahead relative to the past levels. Other ways we can address this is to use same sounds (hearing birds in the forest, to eerie sounds in the ritual based levels) and music (shared and fitting theme for those set of levels)
- Reworking game mechanics like movement to be more consistent or jumping to be more vertical, only if we need to. This would make the game easier and more consistent across difficulties, but should be a last resort as it can influence our existing levels. This would be a viable option if we’re removing all current levels entirely.

**Comment by shoc71** [comment]
> @shoc71 You can close this issue when you have read through it. After we can break it into more manageable and smaller issues

@slysnivy Personally, didn't close this until I got a solid-story line complete.

**Comment by slysnivy** [comment]
@shoc71 I moved this to the discussions page. Also like I said in my comment that you thumbs upped to, we are going to split the issue into smaller and more manageable issues.

**Comment by slysnivy** [comment]
I will do so when I have time tomorrow
