### ISSUE TITLE
Spice Up the Game

### ISSUE THREAD

**Issue by shoc71** [shoc71/Keep-On-Going#445]
Platforms
- moving (x,y) platforms
- appearing and disappearing platforms (one touch or repeat forever)
- portals 

Buttons(?)
- causing the platforms to move

Collectibles
- stars
- bunch of random shapes (might be imported as PNG and treated with a square hitbox)
- money and food (operate the same as stars in terms of gameplay mechanics)

**Comment by shoc71** [comment]
feel free to reject of these ideas or edit my comment above to add more more to the list

**Comment by slysnivy** [comment]
@shoc71 Make sure you pull the PR in the kog editor repository

**Comment by shoc71** [comment]
> @shoc71 Make sure you pull the PR in the kog editor repository

Oh thanks for referring to that. I didn't email about it (or lost it) but I will definitely check it out.

**Comment by slysnivy** [comment]
@shoc71 Would it be ok if I split this issue into smaller issues and move the discussion to the discussions page?

**Comment by slysnivy** [comment]
@shoc71 Still need your input on this

> @shoc71 Would it be ok if I split this issue into smaller issues and move the discussion to the discussions page?

**Comment by shoc71** [comment]
> @shoc71 Would it be ok if I split this issue into smaller issues and move the discussion to the discussions page?

Sorry about not replying to this sooner, but yes you can feel free to close this issue up and make smaller issues if you would like.

**Comment by slysnivy** [comment]
I will now close this issue to split it into multiple more detailed issues

**Comment by slysnivy** [comment]
I put #456, #455, and #454 so far, the rest I will not address until the story files are release (since they're more specific/not generalized and may not appear in the final game)
