### ISSUE TITLE
Level Elements in One or Multiple Files

### ISSUE THREAD

**Issue by slysnivy** [shoc71/Keep-On-Going#450]
The current story suggestions in the document include adding a lot of different level elements, more than I expected. With our current special images, star, non-levels, and level files, and the to be added NPC's, mini bosses, moving platforms, power ups, and enemies, that makes our total files to 18. @shoc71 Would this be too many files to keep separately or should we merge most of them into the non-levels/level files. 

My Suggestion: Personally, I would merge all level-based additions from the new story under the current level files (including stars), and then keep the rest separate.

**Comment by shoc71** [comment]
It would make more sense if we merged all level-related stuff (such as unique platforms looks, buttons, and others) into level-based /non-level files nad keep the rest in separate files for ease of searching and finding.

**Comment by slysnivy** [comment]
Thanks for letting me know
